# Generated by Django 5.2.7 on 2025-10-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('reference_code', models.CharField(help_text='Reference to ANO-14-I (3.1.1)', max_length=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='checklist_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=4)),
                ('status', models.CharField(blank=True, choices=[('S', 'Satisfactory'), ('NS', 'Not Satisfactory')], max_length=3, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Include documentation reference or reason for non-compliance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklist_app.checklistquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='references/')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='checklist_app.operatorresponse')),
            ],
        ),
    ]
